# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: beerproto/v1/mash.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'beerproto/v1/mash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from beerproto.v1 import mash_step_pb2 as beerproto_dot_v1_dot_mash__step__pb2
from beerproto.v1 import measureable_units_pb2 as beerproto_dot_v1_dot_measureable__units__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x65\x65rproto/v1/mash.proto\x12\x0c\x62\x65\x65rproto.v1\x1a\x1c\x62\x65\x65rproto/v1/mash_step.proto\x1a$beerproto/v1/measureable_units.proto\x1a\x1b\x62uf/validate/validate.proto\"\xff\x01\n\x11MashProcedureType\x12\x1b\n\x02id\x18\x01 \x01(\tB\x0b\xbaH\x08r\x03\xb0\x01\x01\xc8\x01\x01R\x02id\x12R\n\x11grain_temperature\x18\x02 \x01(\x0b\x32\x1d.beerproto.v1.TemperatureTypeB\x06\xbaH\x03\xc8\x01\x01R\x10grainTemperature\x12\x14\n\x05notes\x18\x03 \x01(\tR\x05notes\x12\x43\n\nmash_steps\x18\x04 \x03(\x0b\x32\x1a.beerproto.v1.MashStepTypeB\x08\xbaH\x05\x92\x01\x02\x08\x01R\tmashSteps\x12\x1e\n\x04name\x18\x05 \x01(\tB\n\xbaH\x07r\x02\x10\x03\xc8\x01\x01R\x04nameBn\n\x10\x63om.beerproto.v1B\tMashProtoP\x01\xa2\x02\x03\x42XX\xaa\x02\x0c\x42\x65\x65rproto.V1\xca\x02\x0c\x42\x65\x65rproto\\V1\xe2\x02\x18\x42\x65\x65rproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beerproto.v1.mash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.beerproto.v1B\tMashProtoP\001\242\002\003BXX\252\002\014Beerproto.V1\312\002\014Beerproto\\V1\342\002\030Beerproto\\V1\\GPBMetadata\352\002\rBeerproto::V1'
  _globals['_MASHPROCEDURETYPE'].fields_by_name['id']._loaded_options = None
  _globals['_MASHPROCEDURETYPE'].fields_by_name['id']._serialized_options = b'\272H\010r\003\260\001\001\310\001\001'
  _globals['_MASHPROCEDURETYPE'].fields_by_name['grain_temperature']._loaded_options = None
  _globals['_MASHPROCEDURETYPE'].fields_by_name['grain_temperature']._serialized_options = b'\272H\003\310\001\001'
  _globals['_MASHPROCEDURETYPE'].fields_by_name['mash_steps']._loaded_options = None
  _globals['_MASHPROCEDURETYPE'].fields_by_name['mash_steps']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_MASHPROCEDURETYPE'].fields_by_name['name']._loaded_options = None
  _globals['_MASHPROCEDURETYPE'].fields_by_name['name']._serialized_options = b'\272H\007r\002\020\003\310\001\001'
  _globals['_MASHPROCEDURETYPE']._serialized_start=139
  _globals['_MASHPROCEDURETYPE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
