# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: beerproto/v1/packaging_graphic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'beerproto/v1/packaging_graphic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$beerproto/v1/packaging_graphic.proto\x12\x0c\x62\x65\x65rproto.v1\"\xef\x07\n\x14PackagingGraphicType\x12K\n\x08position\x18\x01 \x01(\x0e\x32/.beerproto.v1.PackagingGraphicType.PositionUnitR\x08position\x12\x42\n\x04type\x18\x02 \x01(\x0e\x32..beerproto.v1.PackagingGraphicType.GraphicTypeR\x04type\x12\x1f\n\x0b\x62\x61se64_data\x18\x03 \x01(\tR\nbase64Data\x12\x12\n\x04urls\x18\x04 \x03(\tR\x04urls\x12\x10\n\x03\x64pi\x18\x05 \x01(\x05R\x03\x64pi\x12\x14\n\x05width\x18\x06 \x01(\x03R\x05width\x12\x16\n\x06height\x18\x07 \x01(\x03R\x06height\x12\x42\n\x05units\x18\x08 \x01(\x0e\x32,.beerproto.v1.PackagingGraphicType.UnitsTypeR\x05units\"\x9d\x02\n\x0cPositionUnit\x12\x1d\n\x19POSITION_UNIT_UNSPECIFIED\x10\x00\x12\x1c\n\x18POSITION_UNIT_BODY_FRONT\x10\x01\x12\x1b\n\x17POSITION_UNIT_BODY_BACK\x10\x02\x12\"\n\x1ePOSITION_UNIT_BODY_WRAP_AROUND\x10\x03\x12\x1c\n\x18POSITION_UNIT_NECK_FRONT\x10\x04\x12\x1b\n\x17POSITION_UNIT_NECK_BACK\x10\x05\x12\"\n\x1ePOSITION_UNIT_NECK_WRAP_AROUND\x10\x06\x12\x15\n\x11POSITION_UNIT_CAP\x10\x07\x12\x19\n\x15POSITION_UNIT_CARRIER\x10\x08\"\x9d\x02\n\x0bGraphicType\x12\x1c\n\x18GRAPHIC_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10GRAPHIC_TYPE_SVG\x10\x01\x12\x15\n\x11GRAPHIC_TYPE_SVGZ\x10\x02\x12\x13\n\x0fGRAPHIC_TYPE_AI\x10\x03\x12\x14\n\x10GRAPHIC_TYPE_CDR\x10\x04\x12\x14\n\x10GRAPHIC_TYPE_CDX\x10\x05\x12\x14\n\x10GRAPHIC_TYPE_ODG\x10\x06\x12\x14\n\x10GRAPHIC_TYPE_EPS\x10\x07\x12\x14\n\x10GRAPHIC_TYPE_PDF\x10\x08\x12\x14\n\x10GRAPHIC_TYPE_PNG\x10\t\x12\x14\n\x10GRAPHIC_TYPE_JPG\x10\n\x12\x14\n\x10GRAPHIC_TYPE_GIF\x10\x0b\"M\n\tUnitsType\x12\x1a\n\x16UNITS_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rUNITS_TYPE_MM\x10\x01\x12\x11\n\rUNITS_TYPE_IN\x10\x02\x42z\n\x10\x63om.beerproto.v1B\x15PackagingGraphicProtoP\x01\xa2\x02\x03\x42XX\xaa\x02\x0c\x42\x65\x65rproto.V1\xca\x02\x0c\x42\x65\x65rproto\\V1\xe2\x02\x18\x42\x65\x65rproto\\V1\\GPBMetadata\xea\x02\rBeerproto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beerproto.v1.packaging_graphic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.beerproto.v1B\025PackagingGraphicProtoP\001\242\002\003BXX\252\002\014Beerproto.V1\312\002\014Beerproto\\V1\342\002\030Beerproto\\V1\\GPBMetadata\352\002\rBeerproto::V1'
  _globals['_PACKAGINGGRAPHICTYPE']._serialized_start=55
  _globals['_PACKAGINGGRAPHICTYPE']._serialized_end=1062
  _globals['_PACKAGINGGRAPHICTYPE_POSITIONUNIT']._serialized_start=410
  _globals['_PACKAGINGGRAPHICTYPE_POSITIONUNIT']._serialized_end=695
  _globals['_PACKAGINGGRAPHICTYPE_GRAPHICTYPE']._serialized_start=698
  _globals['_PACKAGINGGRAPHICTYPE_GRAPHICTYPE']._serialized_end=983
  _globals['_PACKAGINGGRAPHICTYPE_UNITSTYPE']._serialized_start=985
  _globals['_PACKAGINGGRAPHICTYPE_UNITSTYPE']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
